// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PasarelaPago.Shared.Models;

public partial class Cliente
{
    public string Cedula { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string Correo { get; set; }

    public string Telefono { get; set; }

    public string Direccion { get; set; }

    public string Ciudad { get; set; }

    public string Provincia { get; set; }

    public string CodigoPostal { get; set; }

    public string Pais { get; set; }

    public virtual ICollection<Pago> Pagos { get; set; } = new List<Pago>();
}