// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PasarelaPago.Shared.Models;

public partial class Pago
{
    public int PagoId { get; set; }

    public string Cedula { get; set; }

    public string NumeroOrden { get; set; }

    public string MetodoPago { get; set; }

    public decimal Monto { get; set; }

    public string Moneda { get; set; }

    public string EstadoTilopay { get; set; }

    public string NumeroAutorizacion { get; set; }

    public string MarcaTarjeta { get; set; }

    public string DatosRespuestaTilopay { get; set; }

    public DateTime FechaTransaccion { get; set; }

    public string StateNonce { get; set; }

    public virtual Cliente CedulaNavigation { get; set; } 
}