// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace PasarelaPago.Shared.Models;

public partial class TilopayDBContext : IdentityDbContext
{
    public TilopayDBContext(DbContextOptions<TilopayDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Cliente> Clientes { get; set; }

    public virtual DbSet<Pago> Pagos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<Cliente>(entity =>
        {
            entity.HasKey(e => e.Cedula).HasName("PK__Clientes__415B7BE4634A9938");

            entity.Property(e => e.Cedula)
                .HasMaxLength(25)
                .IsUnicode(false)
                .HasColumnName("cedula");
            entity.Property(e => e.Apellido)
                .HasMaxLength(50)
                .HasColumnName("apellido");
            entity.Property(e => e.Ciudad)
                .HasMaxLength(50)
                .HasColumnName("ciudad");
            entity.Property(e => e.CodigoPostal)
                .HasMaxLength(20)
                .HasColumnName("codigoPostal");
            entity.Property(e => e.Correo)
                .HasMaxLength(100)
                .HasColumnName("correo");
            entity.Property(e => e.Direccion)
                .HasMaxLength(100)
                .HasColumnName("direccion");
            entity.Property(e => e.Nombre)
                .HasMaxLength(50)
                .HasColumnName("nombre");
            entity.Property(e => e.Pais)
                .HasMaxLength(10)
                .HasColumnName("pais");
            entity.Property(e => e.Provincia)
                .HasMaxLength(50)
                .HasColumnName("provincia");
            entity.Property(e => e.Telefono)
                .HasMaxLength(20)
                .HasColumnName("telefono");
        });

        modelBuilder.Entity<Pago>(entity =>
        {
            entity.HasKey(e => e.PagoId).HasName("PK__Pagos__5736FC0C7878344D");

            entity.HasIndex(e => e.NumeroOrden, "IX_Pagos_NumeroOrden").IsUnique();

            entity.Property(e => e.PagoId).HasColumnName("pagoId");
            entity.Property(e => e.Cedula)
                .IsRequired()
                .HasMaxLength(25)
                .IsUnicode(false)
                .HasColumnName("cedula");
            entity.Property(e => e.DatosRespuestaTilopay).HasColumnName("datosRespuestaTilopay");
            entity.Property(e => e.EstadoTilopay)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("estadoTilopay");
            entity.Property(e => e.FechaTransaccion)
                .HasPrecision(6)
                .HasColumnName("fechaTransaccion");
            entity.Property(e => e.MarcaTarjeta)
                .HasMaxLength(12)
                .IsUnicode(false)
                .HasColumnName("marcaTarjeta");
            entity.Property(e => e.MetodoPago)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("metodoPago");
            entity.Property(e => e.Moneda)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false)
                .HasColumnName("moneda");
            entity.Property(e => e.Monto)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("monto");
            entity.Property(e => e.NumeroAutorizacion)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("numeroAutorizacion");
            entity.Property(e => e.NumeroOrden)
                .IsRequired()
                .HasMaxLength(64)
                .IsUnicode(false)
                .HasColumnName("numeroOrden");
            entity.Property(e => e.StateNonce)
                .IsRequired()
                .HasMaxLength(64)
                .IsUnicode(false)
                .HasDefaultValueSql("(replace(CONVERT([varchar](36),newid()),'-',''))")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Pagos_stateNonce")
                .HasColumnName("stateNonce");

            entity.HasOne(d => d.CedulaNavigation).WithMany(p => p.Pagos)
                .HasForeignKey(d => d.Cedula)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Pagos__cedula__5EBF139D");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}